package uk.bisel.czi.model;

public enum GutComponentName {
	ANUS, ANAL_CANAL, RECTUM, APR, SIGMOID, DESCENDING, TRANSVERSE, ASCENDING, CAECUM, ICV, PROXIMAL, DISTAL, MID, SPENLIC_FLEXURE, HEPATIC_FLEXURE, PROXIMAL_MID_DISTAL;
}
